-- Base46 port of dgox16/oldworld.nvim (default variant)
-- Drop-in for NvChad's <leader>th picker. Picks up oldworld's palette + most
-- syntax/treesitter/UI highlights to match the upstream theme.

local M = {}

-- oldworld palette (default variant)
local p = {
  bg        = "#161617",
  fg        = "#c9c7cd",
  subtext1  = "#b4b1ba",
  subtext2  = "#9f9ca6",
  subtext3  = "#8b8693",
  subtext4  = "#6c6874",
  bg_dark   = "#131314",
  black     = "#27272a",
  red       = "#ea83a5",
  green     = "#90b99f",
  yellow    = "#e6b99d",
  purple    = "#aca1cf",
  magenta   = "#e29eca",
  orange    = "#f5a191",
  blue      = "#92a2d5",
  cyan      = "#85b5ba",
  gray0     = "#18181a",
  gray1     = "#1b1b1c",
  gray2     = "#2a2a2c",
  gray3     = "#313134",
  gray4     = "#3b3b3e",
  gray5     = "#444448",
}

M.base_30 = {
  white         = p.fg,
  darker_black  = p.bg_dark,
  black         = p.bg, -- nvim bg
  black2        = p.gray1,
  one_bg        = p.gray2,
  one_bg2       = p.gray3,
  one_bg3       = p.gray4,
  grey          = p.gray5,
  grey_fg       = p.subtext4,
  grey_fg2      = p.subtext3,
  light_grey    = p.subtext2,
  red           = p.red,
  baby_pink     = p.magenta,
  pink          = p.magenta,
  line          = p.gray0,
  green         = p.green,
  vibrant_green = "#a8c8b3",
  blue          = p.blue,
  nord_blue     = p.blue,
  yellow        = p.yellow,
  sun           = "#f0c8a8",
  purple        = p.purple,
  dark_purple   = "#9c91bf",
  teal          = p.cyan,
  orange        = p.orange,
  cyan          = p.cyan,
  statusline_bg = p.bg_dark,
  lightbg       = p.gray2,
  pmenu_bg      = p.green,
  folder_bg     = p.blue,
}

M.base_16 = {
  base00 = p.bg,
  base01 = p.gray1,
  base02 = p.gray2,
  base03 = p.subtext4,
  base04 = p.subtext3,
  base05 = p.fg,
  base06 = p.subtext1,
  base07 = p.fg,
  base08 = p.red,
  base09 = p.orange,
  base0A = p.yellow,
  base0B = p.green,
  base0C = p.cyan,
  base0D = p.blue,
  base0E = p.purple,
  base0F = p.magenta,
}

M.polish_hl = {
  -- ============================================================
  -- Classic Vim syntax groups (ported from oldworld/groups/syntax.lua)
  -- ============================================================
  syntax = {
    Comment        = { fg = p.subtext3, italic = true },
    Constant       = { fg = p.red },
    String         = { fg = p.green },
    Character      = { fg = p.green },
    Number         = { fg = p.magenta },
    Boolean        = { fg = p.yellow },
    Float          = { fg = p.magenta },
    Identifier     = { fg = p.fg },
    Function       = { fg = p.blue, bold = true },
    Statement      = { fg = p.fg },
    Conditional    = { fg = p.blue },
    Repeat         = { fg = p.purple },
    Label          = { fg = p.purple },
    Operator       = { fg = p.yellow },
    Keyword        = { fg = p.purple },
    Exception      = { fg = p.purple },
    PreProc        = { fg = p.red },
    Include        = { fg = p.purple },
    Define         = { fg = p.red },
    Macro          = { fg = p.red },
    PreCondit      = { fg = p.red },
    Type           = { fg = p.yellow },
    StorageClass   = { fg = p.yellow },
    Structure      = { fg = p.red },
    Typedef        = { fg = p.yellow },
    Special        = { fg = p.blue },
    SpecialChar    = { fg = p.yellow },
    Tag            = { fg = p.yellow },
    SpecialComment = { fg = p.subtext4 },
    Debug          = { fg = p.yellow },
    Error          = { fg = p.orange },
    Todo           = { fg = p.yellow },
  },

  -- ============================================================
  -- Treesitter captures (ported from groups/integrations/treesitter.lua)
  -- ============================================================
  treesitter = {
    ["@comment"]              = { fg = p.subtext3, italic = true },
    ["@constant"]             = { fg = p.red },
    ["@constant.builtin"]     = { fg = p.yellow },
    ["@string"]               = { fg = p.green },
    ["@string.documentation"] = { fg = p.green, italic = true },
    ["@string.regex"]         = { fg = p.purple },
    ["@string.escape"]        = { fg = p.magenta },
    ["@number"]               = { fg = p.magenta },
    ["@boolean"]              = { fg = p.orange },
    ["@function"]             = { fg = p.blue, bold = true },
    ["@function.builtin"]     = { fg = p.blue, bold = true },
    ["@function.call"]        = { fg = p.blue },
    ["@method"]               = { fg = p.blue },
    ["@constructor"]          = { fg = p.subtext3 },
    ["@parameter"]            = { fg = p.fg },
    ["@property"]             = { fg = p.fg },
    ["@variable"]             = { fg = p.fg },
    ["@variable.builtin"]     = { fg = p.purple },
    ["@variable.parameter"]   = { fg = p.fg },
    ["@keyword"]              = { fg = p.purple },
    ["@keyword.function"]     = { fg = p.purple },
    ["@keyword.return"]       = { fg = p.purple },
    ["@keyword.import"]       = { fg = p.red },
    ["@keyword.operator"]     = { fg = p.yellow },
    ["@conditional"]          = { fg = p.blue },
    ["@operator"]             = { fg = p.yellow },
    ["@type"]                 = { fg = p.yellow },
    ["@type.builtin"]         = { fg = p.magenta },
    ["@namespace"]            = { fg = p.red, italic = true },
    ["@punctuation"]          = { fg = p.subtext1 },
    ["@punctuation.delimiter"]= { fg = p.subtext1 },
    ["@punctuation.bracket"]  = { fg = p.subtext3 },
    ["@punctuation.special"]  = { fg = p.subtext1 },
    ["@symbol"]               = { fg = p.yellow },
    ["@tag"]                  = { fg = p.red },
    ["@tag.attribute"]        = { fg = p.cyan, italic = true },
    ["@tag.delimiter"]        = { fg = p.subtext1 },
    -- Markdown headings: matches oldworld's blue-bold style
    ["@markup.heading"]       = { fg = p.fg, bold = true },
    ["@markup.heading.1"]     = { fg = p.blue, bold = true },
    ["@markup.heading.2"]     = { fg = p.blue, bold = true },
    ["@markup.heading.3"]     = { fg = p.blue, bold = true },
    ["@markup.heading.4"]     = { fg = p.blue, bold = true },
    ["@markup.heading.5"]     = { fg = p.blue, bold = true },
    ["@markup.heading.6"]     = { fg = p.blue, bold = true },
    ["@markup.link"]          = { fg = p.subtext1 },
    ["@markup.link.label"]    = { fg = p.red },
    ["@markup.link.url"]      = { fg = p.purple },
    ["@markup.list"]          = { fg = p.subtext4, bold = true },
  },

  -- ============================================================
  -- Editor / UI groups (ported from groups/editor.lua)
  -- ============================================================
  defaults = {
    Normal           = { fg = p.fg, bg = p.bg },
    NormalNC         = { fg = p.fg, bg = p.bg_dark },
    NormalFloat      = { fg = p.fg, bg = p.gray0 },
    FloatBorder      = { fg = p.gray3, bg = p.bg },
    CursorLine       = { bg = p.gray1 },
    CursorLineNr     = { fg = p.subtext1 },
    LineNr           = { fg = p.gray5 },
    SignColumn       = { fg = p.subtext4, bg = p.bg },
    FoldColumn       = { fg = p.subtext4, bg = p.bg },
    Folded           = { fg = p.gray4 },
    EndOfBuffer      = { fg = p.bg },
    VertSplit        = { fg = p.gray2 },
    WinSeparator     = { fg = p.gray2 },
    Visual           = { bg = p.gray4 },
    Search           = { fg = p.yellow, bg = p.gray2 },
    IncSearch        = { fg = p.bg, bg = p.yellow },
    CurSearch        = { fg = p.bg, bg = p.yellow },
    MatchParen       = { fg = p.yellow, underline = true },
    Pmenu            = { fg = p.fg, bg = p.gray1 },
    PmenuSel         = { fg = p.fg, bg = p.gray3 },
    PmenuSbar        = { bg = p.gray2 },
    PmenuThumb       = { bg = p.gray3 },
    Directory        = { fg = p.purple },
    Title            = { fg = p.green },
    Question         = { fg = p.purple },
    ErrorMsg         = { fg = p.orange },
    WarningMsg       = { fg = p.yellow },
    NonText          = { fg = p.subtext4 },
    SpecialKey       = { fg = p.subtext2 },
    QuickFixLine     = { fg = p.red, bg = p.gray2 },
    -- diff
    DiffAdd          = { fg = p.green,  bg = "#1f2a22" },
    DiffChange       = { fg = p.orange, bg = "#2a221d" },
    DiffDelete       = { fg = p.red,    bg = "#2a1d22" },
    DiffText         = { fg = p.bg,     bg = p.orange },
    diffAdded        = { fg = p.green },
    diffRemoved      = { fg = p.red },
    diffChanged      = { fg = p.yellow },
  },
}

M.type = "dark"

M = require("base46").override_theme(M, "oldworld")

return M
